### ISSUE TITLE
server console says, failed to load.

### ISSUE THREAD

**Issue by originalwhitestar** [bcool/ULX-Global-Ban#10]
hello, the server cant include the files, it says "Missing mysqloo.lua" but it is still in the folder.

and i looked into the files,

ulx_globalban.lua says

-- ULX GlobalBan System
-- Adobe and NigNog
------------------

//Load the inital file for the server!
if SERVER then
	print('[ULX GB] - Loading.....');
	include('globalban/gb_generic.lua');
	include('globalban/gb_mysqloo.lua');
end

and in the console it looks like "[ULX GB] Loading failed! couldnt include gb_mysqloo.lua!(file not found) what to do?

**Comment by bcool** [comment]
MySQLOO is not installed correctly, check the modules forum page for installation instructions.
