### ISSUE TITLE
Is not kicking anymore

### ISSUE THREAD

**Issue by Thiritin** [bcool/ULX-Global-Ban#20]
Since the Gmod update, i ban someone and global ban isn't kicking him. he just stay on the server until i kick him.

**Comment by Jeffx539** [comment]
Sorry for the delayed response, do you have any log files that you can provide ? Kinda flying dark here

Regards,
Jeff

**Comment by Thiritin** [comment]
Thanks for the answer, i fixed the problem. There were no errors. 

But i expiring this Problem when i change the kick message when you get banned.

Lines:

```
-- Regardless of outcome Kick player From Server
RunConsoleCommand('kickid',steamid,"You've been banned from the server.");
```

**Comment by Jeffx539** [comment]
I'll have a look into it when I get off the train, will report back in about an hour.

Cheers

**Comment by Thiritin** [comment]
Okay Thanks

**Comment by Thiritin** [comment]
Does work now.
